### ISSUE TITLE
Consider getting rid of REFRESH_SECONDS

### ISSUE THREAD

**Issue by mmilata** [jvstein/bitcoin-prometheus-exporter#12]
Most Prometheus exporters fetch the metrics immediately after being queried, possibly with some rate limiting. This way the refresh interval doesn't have to be configured in two places, i.e. scraper config as well as exporter config.

**Comment by jvstein** [comment]
This is one of the design decisions that was inherited from the parent project. I suspect one of the main reasons for having the exporter scrape on a predictable schedule was for a more predictable load on the bitcoin server along with keeping `scrape_duration_seconds` low on the prometheus side. My refresh rate is longer than my prometheus scrape duration because I don't feel like I need very fast metrics for this exporter.

My metrics show that the duration of the refresh has been very stable, and around 1s. It seems totally reasonable to make it a dynamic response, but I might want to retain the existing behavior, personally.

It would nice to see your value for `rate(bitcoin_exporter_process_time_total[10m]) * 60` (where `60` is from my `REFRESH_SECONDS` value). That will be the number of seconds it takes to do the full metrics refresh.

**Comment by mmilata** [comment]
Sure, it's quite a big change for not that much benefit. I think the predictable (or at least bounded) load can still be achieved by setting a minimal interval (and returning cached results when requests come more often).

The value oscillates between 0.4 and 0.8 (for `REFRESH_SECONDS`=120).

**Comment by nicolasburtey** [comment]
agree with mmilata. scrape interval is typically a set on the prometheus server. having another layer of caching from the exporter should not be necessary

**Comment by jvstein** [comment]
Feel free to implement and submit a PR. I don't need this functionality personally so its nowhere near the top of my TODO list.

**Comment by jvstein** [comment]
Fixed in 356f5f3e3945bb9300039f315c1b9524dba8a049 and included in the 0.7.0 release.
